name: Convert dependabot PR to Jira ticket (specific team)
# The source code for this action can be found here: https://github.com/askyourteam-nz/.github

on:
  pull_request:
    types:
      - opened
    branches:
      - staging

env:
  JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
  JIRA_USER_EMAIL: ${{ vars.JIRA_USER_EMAIL }}
  JIRA_ISSUE_TYPE: ${{ vars.JIRA_ISSUE_TYPE }}
  # Reference the specific team variable you want to create the issue for:
  JIRA_PROJECT: ${{ vars.JIRA_PROJECT_KEY_CHARLIES }}
  # JIRA_PROJECT: ${{ vars.JIRA_PROJECT_KEY_PHOENIX }}

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3.0.1
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create-ticket-for-charlies
      uses: atlassian/gajira-create@v3.0.1
      with:
        project: ${{ env.JIRA_PROJECT }}
        issuetype: ${{ env.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}
